import React, { useEffect, useRef, useState } from 'react';
import { hydrateRoot, createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowUp, Phone, MapPin, Clock, Leaf, BowlFood, List, X, EnvelopeSimple, Sun, Moon, FacebookLogo } from '@phosphor-icons/react';
import './fonts.css';
import './style.css';
import { copy, dishes } from './data';

  // Use the local German dial string for Safari/iPhone compatibility.
  const phone = 'tel:039464159682';
const maps = 'https://www.google.com/maps/search/?api=1&query=Moc+83+Steinweg+79+06484+Quedlinburg';
const facebook = 'https://www.facebook.com/tastyinyourlifr';
export function App({initialLang='de',initialCategory=0}={}){
  const [lang,setLang]=useState(initialLang);
  // The brief explicitly requests Tobisu's dark palette. A light alternative remains available.
  const [theme,setTheme]=useState('dark');
  const [nav,setNav]=useState(false);
  const [category,setCategory]=useState(initialCategory);
  const [modal,setModal]=useState(null);
  const dialog=useRef(null); const t=copy[lang];
  useEffect(()=>{document.documentElement.dataset.enhanced='true';if(new URLSearchParams(window.location.search).get('booking')==='1')setModal('booking');},[]);
  useEffect(()=>{document.documentElement.lang=lang; document.title=lang==='de'?'Mộc 83 | Vietnamesische Küche & Sushi in Quedlinburg':'Mộc 83 | Vietnamese Kitchen & Sushi in Quedlinburg'; document.querySelector('meta[name="description"]').content=lang==='de'?'Vietnamesische Küche und Sushi bei Mộc 83, Steinweg 79, Quedlinburg. Tisch reservieren: 03946 4159682.':'Vietnamese food and sushi at Mộc 83, Steinweg 79, Quedlinburg. Book a table: 03946 4159682.';},[lang]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
  useEffect(()=>{ if(modal){dialog.current.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';}; },[modal]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.09});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[]);
  const mailHref=`mailto:legiahan0102@gmail.com?subject=${encodeURIComponent(t.emailSubject)}&body=${encodeURIComponent(t.emailBody)}`;
  const openMenu=()=>{window.location.href='menu.html';};
  return <>
    <a className="skip" href="#main">{lang==='de'?'Zum Inhalt':'Skip to content'}</a>
    <header className="header"><div className="nav-wrap">
      <a href="#" className="brand"><img src="assets/logo-small.webp" alt="" width="58" height="58"/><span>MỘC 83<small>{t.cuisine}</small></span></a>
      <nav className={nav?'nav open':'nav'} aria-label={lang==='de'?'Hauptnavigation':'Main navigation'} id="navigation">
        {[['restaurant',t.restaurant],['menu',t.menu],['drinks',t.drinks],['contact',t.visit]].map(([id,label])=><a key={id} href={id==='menu'?'menu.html':`#${id}`} onClick={()=>setNav(false)}>{label}</a>)}
      </nav>
      <div className="nav-actions"><div className="language" aria-label="Language"><button lang="de" aria-pressed={lang==='de'} onClick={()=>setLang('de')}>DE</button><span>/</span><button lang="en" aria-pressed={lang==='en'} onClick={()=>setLang('en')}>EN</button></div><button className="nav-book" onClick={()=>setModal('booking')}>{t.reserve}<ArrowUpRight size={16}/></button><button className="hamburger icon-button" aria-label={nav?t.close:t.mobileNav} aria-expanded={nav} aria-controls="navigation" onClick={()=>setNav(!nav)}>{nav?<X size={24}/>:<List size={24}/>}</button></div>
    </div></header>
    <main id="main">
      <section className="hero" aria-labelledby="hero-title">
        <div className="hero-image"><picture><source type="image/avif" srcSet="assets/sushi-480.avif 480w, assets/sushi-640.avif 640w, assets/sushi-960.avif 960w, assets/sushi-1280.avif 1280w" sizes="(max-width: 767px) 100vw, 72vw"/><img src="assets/sushi.webp" srcSet="assets/sushi-480.webp 480w, assets/sushi-640.webp 640w, assets/sushi-960.webp 960w, assets/sushi-1280.webp 1280w, assets/sushi.webp 1536w" sizes="(max-width: 767px) 100vw, 72vw" alt={lang==='de'?'Sushi mit Lachs und Avocado, KI-Motivbild':'Salmon and avocado sushi, AI illustration'} width="1536" height="1024" fetchPriority="high"/></picture></div>
        <div className="hero-content wrap"><p className="eyebrow"><span className="little-line"/>{t.eyebrow}</p><h1 id="hero-title">{t.hero.split('\n').map((line,i)=><React.Fragment key={line}>{i>0&&<br/>}{line}</React.Fragment>)}</h1><p className="hero-description">{t.heroText}</p><div className="hero-actions"><a className="button gold" href="#menu">{t.explore}<ArrowUpRight size={19}/></a><button className="text-button" onClick={()=>setModal('booking')}>{t.reserve}<ArrowRight size={17}/></button></div><div className="hero-signature"><span>越南料理</span><span>VIETNAMESE SOUL.<br/>JAPANESE CRAFT.</span></div></div>
      </section>
      <div className="info-strip wrap"><a href={maps} target="_blank" rel="noreferrer"><MapPin size={23}/><span><small>{t.address}</small>Steinweg 79, Quedlinburg</span><ArrowUpRight size={18}/></a><div><Clock size={23}/><span><small>{t.hours}</small>11:00 - 15:00 <span className="time-separator">/</span> 17:00 - 22:00</span></div><a href={phone}><Phone size={23}/><span><small>{t.reserve}</small>03946 4159682</span><ArrowUpRight size={18}/></a></div>
      <section className="story section wrap" id="restaurant"><div className="story-visual reveal"><img src="assets/pho.webp" srcSet="assets/pho-480.webp 480w, assets/pho-640.webp 640w, assets/pho-960.webp 960w, assets/pho.webp 1254w" sizes="(max-width: 767px) calc(100vw - 40px), 50vw" alt={lang==='de'?'Phở mit Rindfleisch und frischen Kräutern':'Pho with beef and fresh herbs'} width="1254" height="1254" loading="lazy"/><div className="image-caption"><span>Phở Hà Nội</span><span>VIETNAMESE COMFORT FOOD</span></div></div><div className="story-copy reveal"><p className="eyebrow">{t.welcome}</p><h2>{t.storyTitle}</h2><p>{t.story}</p><p>{t.story2}</p><div className="values"><div><BowlFood size={26}/><span><strong>{t.fresh}</strong><small>{t.freshText}</small></span></div><div><Leaf size={26}/><span><strong>{t.veggie}</strong><small>{t.veggieText}</small></span></div></div><a className="underlined-link" href="#contact">{t.storyLink}<ArrowUpRight size={18}/></a></div></section>
      <section className="menu-section section" id="menu"><div className="wrap"><div className="section-heading reveal"><p className="eyebrow">{t.menuEye}</p><h2>{t.menuTitle}</h2><p>{t.menuText}</p></div><div className="tabs" role="tablist" aria-label={t.menu}>{t.categories.map((label,i)=><button id={`tab-${i}`} aria-controls="dish-panel" role="tab" aria-selected={category===i} tabIndex={category===i?0:-1} key={label} onClick={()=>setCategory(i)} onKeyDown={e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%4;else if(e.key==='ArrowLeft')next=(i+3)%4;else if(e.key==='Home')next=0;else if(e.key==='End')next=3;else return;e.preventDefault();setCategory(next);document.getElementById(`tab-${next}`).focus();}}>{label}</button>)}</div>
      <div className="menu-layout" role="tabpanel" id="dish-panel" aria-labelledby={`tab-${category}`}><div className="menu-photo"><img key={category} src={category===1?'assets/sushi.webp':category===2?'assets/vorspeisen-1280.webp':category===3?'assets/drinks.webp':'assets/pho.webp'} srcSet={category===2?'assets/vorspeisen-640.webp 640w, assets/vorspeisen-960.webp 960w, assets/vorspeisen-1280.webp 1280w':`${category===1?'assets/sushi':category===3?'assets/drinks':'assets/pho'}-480.webp 480w, ${category===1?'assets/sushi':category===3?'assets/drinks':'assets/pho'}-960.webp 960w, ${category===1?'assets/sushi':category===3?'assets/drinks':'assets/pho'}-1280.webp 1280w`} sizes="(max-width: 767px) calc(100vw - 40px), 40vw" alt={t.categories[category]} width="800" height="900" loading="lazy" decoding="async"/><div className="menu-photo-caption"><span>MỘC 83</span><p>{t.categories[category]}</p></div></div><div className="dish-list">{dishes[category].map(d=><article className="dish" key={d.name}><div className="dish-heading"><h3>{d.name}</h3><span className="price">{d.from&&<small>{t.from} </small>}{d.price} €</span></div><p>{d[lang]}</p><small className="dish-detail">{lang==='de'?d.detailDe:d.detailEn}</small></article>)}<button className="underlined-link" onClick={openMenu}>{t.allMenu}<ArrowUpRight size={19}/></button></div></div><div className="menu-bottom"><p>{t.menuNote}</p><button className="button outline" onClick={openMenu}>{t.fullMenu}<List size={20}/></button></div></div></section>
      <section className="sushi-gallery section wrap" aria-labelledby="sushi-gallery-title"><div className="gallery-heading reveal"><p className="eyebrow">{lang==='de'?'Frisch aus unserer Küche':'Fresh from our kitchen'}</p><h2 id="sushi-gallery-title">{lang==='de'?'Sushi, das wir wirklich servieren.':'Sushi we actually serve.'}</h2><p>{lang==='de'?'Ein Blick auf unsere Platten, Rollen und frischen Zutaten – direkt aus der Küche von Mộc 83.':'A look at our platters, rolls and fresh ingredients, straight from the Mộc 83 kitchen.'}</p></div><div className="gallery-grid reveal">{[1,2,3,4,5,6].map((number,index)=><figure className={`gallery-item gallery-item-${index+1}`} key={number}><img src={`assets/sushi-gallery-${String(number).padStart(2,'0')}.webp`} srcSet={`assets/sushi-gallery-${String(number).padStart(2,'0')}-480.webp 480w, assets/sushi-gallery-${String(number).padStart(2,'0')}-960.webp 960w`} sizes="(max-width: 767px) 78vw, 40vw" width="960" height="1280" decoding="async" alt={lang==='de'?`Sushi-Kreation von Mộc 83, Ansicht ${number}`:`Mộc 83 sushi creation, view ${number}`} loading="lazy"/></figure>)}</div></section>
      <section className="drinks section wrap" id="drinks"><div className="drinks-copy reveal"><p className="eyebrow">{t.drinksEye}</p><h2>{t.drinksTitle}</h2><p>{t.drinksText}</p><div className="drink-highlight"><span>Passionfruit<small>{lang==='de'?'Limette. Maracuja. Ein bisschen Leichtigkeit.':'Lime. Passion fruit. A little refreshment.'}</small></span><strong>6,90 €</strong></div><a className="underlined-link" href="#menu" onClick={()=>setCategory(3)}>{t.drinksLink}<ArrowUpRight size={19}/></a></div><figure className="drinks-visual reveal"><img src="assets/drinks.webp" srcSet="assets/drinks-480.webp 480w, assets/drinks-640.webp 640w, assets/drinks-960.webp 960w, assets/drinks-1280.webp 1280w, assets/drinks.webp 1536w" sizes="(max-width: 767px) calc(100vw - 40px), 50vw" alt={lang==='de'?'Maracuja-Limonade und vietnamesischer Kaffee, KI-Motivbild':'Passion fruit soda and Vietnamese coffee, AI illustration'} width="1536" height="1024" loading="lazy"/><figcaption>{lang==='de'?'Hausgemacht. Für Ihren Moment.':'Homemade. For your moment.'}</figcaption></figure></section>
      <section className="moment wrap reveal"><p className="eyebrow">{t.momentEye}</p><h2>{t.momentTitle}</h2><p>{t.momentText}</p><button className="button gold" onClick={()=>setModal('booking')}>{t.reserve}<ArrowUpRight size={20}/></button></section>
      <section className="contact section wrap" id="contact"><div className="contact-intro reveal"><p className="eyebrow">{t.contactEye}</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><a className="phone-display" href={phone}>03946 4159682<ArrowUpRight size={27}/></a><a className="underlined-link" href={mailHref}>{t.email}<EnvelopeSimple size={18}/></a></div><div className="contact-details reveal"><div><MapPin size={24}/><div><h3>{t.address}</h3><p>Mộc 83<br/>Steinweg 79<br/>06484 Quedlinburg</p><a className="underlined-link" href={maps} target="_blank" rel="noreferrer">{t.direction}<ArrowUpRight size={17}/></a></div></div><div><Clock size={24}/><div><h3>{t.hours}</h3><p className="hours-row"><span>{t.lunch}</span><span>11:00 - 15:00</span></p><p className="hours-row"><span>{t.evening}</span><span>17:00 - 22:00</span></p></div></div><div><FacebookLogo size={24}/><div><h3>{t.follow}</h3><a className="underlined-link" href={facebook} target="_blank" rel="noreferrer">{t.facebook}<ArrowUpRight size={17}/></a></div></div></div></section>
    </main>
    <footer className="footer wrap"><div className="footer-top"><a href="#" className="brand"><img src="assets/logo-small.webp" alt="" width="48" height="48"/><span>MỘC 83<small>{t.cuisine}</small></span></a><span className="footer-greeting">Hẹn gặp lại.<small>{lang==='de'?'Bis zum nächsten Mal.':'Until next time.'}</small></span><a href="#" className="icon-button" aria-label={t.back}><ArrowUp size={22}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Mộc 83. {t.rights}</span><span className="photo-note">{t.photoNote}</span><button className="icon-button theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={t.theme}>{theme==='dark'?<Sun size={20}/>:<Moon size={20}/>}</button></div></footer>
    <nav className="mobile-bar" aria-label={lang==='de'?'Schnellkontakt':'Quick contact'}><a href={phone} aria-label={`${t.call}: 03946 4159682`}><Phone size={20}/><span>{lang==='de'?'Anrufen':'Call us'}</span></a><a href={maps} target="_blank" rel="noreferrer" aria-label={t.direction}><MapPin size={20}/><span>{lang==='de'?'Route':'Directions'}</span></a><a href="#contact" onClick={e=>{e.preventDefault();setNav(false);setModal('booking');}}><span><ArrowUpRight size={20}/></span><span>{t.reserve}</span></a></nav>
    <dialog aria-label={t.bookingTitle} ref={dialog} className="dialog booking-dialog" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null);}}><div className="dialog-inner"><button className="dialog-close icon-button" aria-label={t.close} onClick={()=>setModal(null)}><X size={25}/></button><p className="eyebrow">MỘC 83 · QUEDLINBURG</p><h2>{t.bookingTitle}</h2><p>{t.bookingInfo}</p><div className="booking-hours"><Clock size={21}/>11:00 - 15:00 / 17:00 - 22:00</div><a className="button gold" href={phone}><Phone size={20}/>03946 4159682</a><a className="button outline" href={mailHref}><EnvelopeSimple size={20}/>{t.email}</a></div></dialog>
  </>;
}
if(typeof document!=='undefined'){
  const root=document.getElementById('root');
  if(root.hasChildNodes())hydrateRoot(root,<App/>);
  else createRoot(root).render(<App/>);
}



